Addition of function: tax_spellcheck
palaeoverse-community/palaeoverse pull request #30
Opened 2022-07-26 13:58 UTC by jf15558

# Function name
tax_spellcheck

## Description
tax_spellcheck provides a quick means of identifying potential spelling variations of the same taxon name.
Taxon names are compared groupwise (alphabetically, or by higher taxonomy) using a string distance metric
developed with short, human-typed strings in mind. Additional filtering options are also provided, tailored
to the specific challenges presented by taxon names.

CAVEAT 1: the package relies on the stringdist package. Use of this dependency was discussed with developer
Lewis Jones and the decision was made to permit its use, with the agreement by J.F.S to implement any
bug fixes as needed.

CAVEAT 2: the function currently contains a single warning. This is set to silent by default, but if made verbose
it will warn the user of any non alpha characters in the taxon names as these can diminish the quality of
comparisons. This warning statement could be removed, but as the function is not designed to be part of
automated pipelines and is instead explicitly for guiding the user towards potentially erroneous data, its
inclusion might be justifiable here as the user is expected to consiously heed the function output.

## Motivation and Context
Flagging by this function enables user correction of their data, so that a given taxon is properly represented
by all of its occurrences. Function addition was invited by developer Lewis Jones.

## Checklist before requesting a review
- [y] I have read palaeoverse's [standards and structure](https://github.com/palaeoverse-community/palaeoverse/raw/main/man/tutorials/structure-and-standards.pdf) 
- [y] I have performed a self-review of my code.
- [y] I have added function documentation.
- [y] I have provided sufficient examples of implementation.
- [y] If it is a core feature, I have added thorough tests.

2022-07-26 14:58 UTC, willgearty commented
Thanks for the contribution @jf15558! Before we go ahead with the review, could you please increase the test coverage? We're trying to maintain >90% test coverage for the package. It looks like you're currently doing a great job testing the error handling, so I think just adding one or two non-error tests should increase your coverage dramatically.

2022-07-29 19:01 UTC, LewisAJones reviewed
Hey @jf15558! As @willgearty said, thanks for this great contribution! Very exciting to have our first contributor to the palaeoverse R package :-)

I know you're pressed for time with heading off for fieldwork soon, so I've given some general comments for now. I will go through the code a bit more early next week. From a quick play though, the function seems to work pretty well! It took me a little while to get familiar with some of the functionality, but I think this is just a case of tidying up the documentation. See my general comments below, and I'll get back to you with more later!

Thanks again for this contribution!

2022-07-30 15:39 UTC, LewisAJones reviewed
Hi Joe, I got a chance to look through bits of your code today, please see attached for comments. Feel free to tell me if I've misunderstood anything! We're trying to make things much more of a dialogue here (probably no one is going to understand your code as well as you!).

2022-07-30 15:39 UTC, LewisAJones commented on R/tax_spellcheck.R
> +  no_group <- which(is.na(x[,"groups"]))
Is this working as it should? Also, we often have data (e.g. PBDB) that just have empty rows, interpreted as "" in R. We might need something else here to capture that (I experienced this issue with your brachs example).

2022-08-01 12:15 UTC, jf15558 commented
Hi Lewis

Many thanks for your comments, and nice spot with that bug in the removal of equivalent entries - had totally missed that! I think I've made all the necessary changes and they will definitely filter into fossilbrush too. I've still got a solid 5 days before I go on fieldwork to continue making updates as needed.

Best,
Joe
________________________________
From: Lewis A. Jones ***@***.***>
Sent: 30 July 2022 16:40
To: palaeoverse-community/palaeoverse ***@***.***>
Cc: Joe Flannery-Sutherland ***@***.***>; Mention ***@***.***>
Subject: Re: [palaeoverse-community/palaeoverse] Addition of function: tax_spellcheck (PR #30)


@LewisAJones commented on this pull request.

Hi Joe, I got a chance to look through bits of your code today, please see attached for comments. Feel free to tell me if I've misunderstood anything! We're trying to make things much more of a dialogue here (probably no one is going to understand your code as well as you!).

________________________________

In R/tax_spellcheck.R<https://github.com/palaeoverse-community/palaeoverse/pull/30#discussion_r933797416>:

> +  # groups = NULL

+  # dissim = 0.01

+  # pref = suff = NULL

+  # verbose = FALSE

+  # srt = 1

+  # end = 0

+

+  # ARGUMENT CHECKS --------------------------------------------------------- #

+

+  # x: a data.frame with at least one row

+  if(!exists("x")) {

+    stop("Please supply 'x' as a data.frame containing a column of taxon names,

+         and optionally a column denoting their higher classification")

+  }

+  if(!is.data.frame(x)) {

+    stop("Please supply 'x' as a data.frame containing a column of taxon names,



Couldn't these two if functions be merged into one with an or? (lines 110–117)?

________________________________

In R/tax_spellcheck.R<https://github.com/palaeoverse-community/palaeoverse/pull/30#discussion_r933797841>:

> +    stop("Please supply 'x' as a data.frame containing a column of taxon names,

+         and optionally a column denoting their higher classification")

+  }

+  if(!is.data.frame(x)) {

+    stop("Please supply 'x' as a data.frame containing a column of taxon names,

+         and optionally a column denoting their higher classification")

+  }

+  if(nrow(x) == 0) {

+    stop("'x' does not contain any data")

+  }

+  if(is.null(colnames(x))) {

+    stop("'x' does not contain any column names")

+  }

+

+  # names: a 1L character vector denoting a character column in x

+  if(!exists("names")) {



Should lines 126 to 130 be merged into one if function?

________________________________

In R/tax_spellcheck.R<https://github.com/palaeoverse-community/palaeoverse/pull/30#discussion_r933798193>:

> +    stop("The 'names' column in 'x' must contain character data")

+  }

+  if(all(is.na(x[,names]))) {

+    stop("All taxon name entries in the specified column are NA")

+  }

+

+  # groups: If not NULL, a 1L character vector denoting a character column in x

+  if(!is.null(groups)) {

+    if(length(groups) != 1 | !is.character(groups)) {

+      stop("Please specify 'groups' as a single column name in 'x")

+    }

+    if(!groups %in% colnames(x)) {

+      stop("'groups' is not a column name in 'x'")

+    }

+    if(!is.character(x[,groups])) {

+      stop("The 'groups' column in 'x' must contain character data")



⬇️ Suggested change

-      stop("The 'groups' column in 'x' must contain character data")

+      stop("The 'groups' column in 'x' must contain data of class character")



________________________________

In R/tax_spellcheck.R<https://github.com/palaeoverse-community/palaeoverse/pull/30#discussion_r933798345>:

> +  if(is.null(colnames(x))) {

+    stop("'x' does not contain any column names")

+  }

+

+  # names: a 1L character vector denoting a character column in x

+  if(!exists("names")) {

+    stop("Please specify 'names' as a single column name in 'x'")

+  }

+  if(length(names) != 1 | !is.character(names)) {

+    stop("Please specify 'names' as a single column name in 'x'")

+  }

+  if(!names %in% colnames(x)) {

+    stop("'names' is not a column name in 'x'")

+  }

+  if(!is.character(x[,names])) {

+    stop("The 'names' column in 'x' must contain character data")



⬇️ Suggested change

-    stop("The 'names' column in 'x' must contain character data")

+    stop("The 'names' column in 'x' must contain data of class character")



________________________________

In R/tax_spellcheck.R<https://github.com/palaeoverse-community/palaeoverse/pull/30#discussion_r933798504>:

> +  }

+

+  # names: a 1L character vector denoting a character column in x

+  if(!exists("names")) {

+    stop("Please specify 'names' as a single column name in 'x'")

+  }

+  if(length(names) != 1 | !is.character(names)) {

+    stop("Please specify 'names' as a single column name in 'x'")

+  }

+  if(!names %in% colnames(x)) {

+    stop("'names' is not a column name in 'x'")

+  }

+  if(!is.character(x[,names])) {

+    stop("The 'names' column in 'x' must contain character data")

+  }

+  if(all(is.na(x[,names]))) {



How are NAs handled? Say only one or two entries contain NA

________________________________

In R/tax_spellcheck.R<https://github.com/palaeoverse-community/palaeoverse/pull/30#discussion_r933798904>:

> +      stop("Please specify 'groups' as a single column name in 'x")

+    }

+    if(!groups %in% colnames(x)) {

+      stop("'groups' is not a column name in 'x'")

+    }

+    if(!is.character(x[,groups])) {

+      stop("The 'groups' column in 'x' must contain character data")

+    }

+    groups <- x[,groups]

+  } else {

+    groups <- substring(x[,names], 1, 1)

+  }

+

+  # dissim: a 1L numeric > 0 and < 1

+  if(!is.numeric(dissim) | length(dissim) != 1) {

+    stop("'dissim' must be a single numeric, greater than 0, less than 1")



See previous documentation comment about the usage of 0–1. I am happy with whatever you decide but we should make things more easily interpretable/obvious. Not everyone will read documentation in detail so for percentages people will expect 0 to 100.

________________________________

In R/tax_spellcheck.R<https://github.com/palaeoverse-community/palaeoverse/pull/30#discussion_r933799205>:

> +  } else {

+    groups <- substring(x[,names], 1, 1)

+  }

+

+  # dissim: a 1L numeric > 0 and < 1

+  if(!is.numeric(dissim) | length(dissim) != 1) {

+    stop("'dissim' must be a single numeric, greater than 0, less than 1")

+  }

+  if(dissim >= 1 | dissim <= 0) {

+    stop("'dissim' must be a single numeric, greater than 0, less than 1")

+  }

+

+  # srt: a 1L integer >= 0

+  if(!is.null(srt)) {

+    if(!is.numeric(srt) | length(srt) != 1) {

+      stop("'srt' must be a single positive integer, or zero")



Potential issues with behaviour with strings of different lengths? This will be edge cases, but something to consider (say srt/end = 8?).

________________________________

In R/tax_spellcheck.R<https://github.com/palaeoverse-community/palaeoverse/pull/30#discussion_r933799569>:

> +    }

+  }

+

+  # end: a 1L integer >= 0

+  if(!is.null(end)) {

+    if(!is.numeric(end) | length(end) != 1) {

+      stop("'end' must be a single positive integer, or zero")

+    }

+    if(end < 0 | end %% 1 != 0) {

+      stop("'end' must be a single positive integer, or zero")

+    }

+  }

+

+  # pref: If not NULL, a character vector

+  if(!is.null(pref)) {

+    if(!is.vector(pref)) {



Couldn't lines 188–191 be combined into a single if function?

________________________________

In R/tax_spellcheck.R<https://github.com/palaeoverse-community/palaeoverse/pull/30#discussion_r933799620>:

> +  }

+

+  # pref: If not NULL, a character vector

+  if(!is.null(pref)) {

+    if(!is.vector(pref)) {

+      stop("'pref' must be a character vector or NULL")

+    }

+    if(!is.character(pref)) {

+      stop("'pref' must be a character vector or NULL")

+    }

+    pref <- na.omit(pref)

+  }

+

+  # suff: If not NULL, a character [...]

2022-08-03 13:30 UTC, LewisAJones requested changes
Hi Joe,

Thanks for the updates, I don't see any major issues with the code. My requested changes are now mainly related to the documentation and implementation. See attached for specific comments. Please try to commit suggestions where possible and resolve the comment, otherwise reply to comments/suggestions if you want to chat about these more.

Please ensure to fix all outstanding lint issues (you can see these by going to checks > lint > lint, and checking your submission files) and remember to run the document() function.

As discussed offline, could you also email across (to me) a short paragraph on the function describing its purpose/functionality/implementation? This can then be integrated into the manuscript! :-) 

Thanks again,

Lewis

p.s. I hope fieldwork prep is going well!

2022-08-03 13:30 UTC, LewisAJones commented on R/tax_check.R
> +  sim <- 1 - (sim / 100)
I didn't really intend for you to change this from dissimilarity to similarity, just more to clarify that if percentages are desired it should be given as a percentage (whether similarity or dissimilarity). It is fine as similarity but we should make this conversion clear in the details as the the Jaro metric returns dissimilarity?

2022-08-03 13:45 UTC, jf15558 commented on R/tax_check.R
> +#' groups or within alphabetical groups if higher taxonomy is not provided
Implemented

2022-08-03 13:45 UTC, jf15558 commented on R/tax_check.R
> +#' one another (e.g., 'family', 'order', etc.). NA values or blank strings in
Implemented

2022-08-03 13:46 UTC, jf15558 commented on R/tax_check.R
> +#' the name and group columns (i.e. '', ' ') will be ignored.
Implemented

2022-08-03 13:48 UTC, jf15558 commented on R/tax_check.R
> +#' synonyms be reported.
Typo corrected

2022-08-03 13:49 UTC, jf15558 commented on R/tax_check.R
> +#' @param sim \code{numeric}. The percentage similarity, above which potential
Implemented

2022-08-03 13:50 UTC, jf15558 commented on R/tax_check.R
> +#' spuriously high similarities. Synonyms will be filtered out out if only one
Implemented

2022-08-03 13:51 UTC, jf15558 commented on R/tax_check.R
> +#' spuriously high similarities. Synonyms will be filtered out out if only one
Implemented

2022-08-03 13:51 UTC, jf15558 commented on R/tax_check.R
> +#' character check be reported to the user. If `TRUE`, the result will only be
Implemented

2022-08-03 13:52 UTC, jf15558 commented on R/tax_check.R
> +#' supplied, e.g. 'Pro', 'Proto'. High similarity matches resulting from high
Used 'and' instead of 'or' to make it clearer that this is a paired example

2022-08-03 13:54 UTC, jf15558 commented on R/tax_check.R
> +#' #' @section Reference:
Implemented. I think the reference is worth keeping though, as it contains some good documentation on different string distance metrics

2022-08-03 14:00 UTC, jf15558 commented on R/tax_check.R
> +#' column which contain non- letter characters. This element is `NULL` if none
Implemented

2022-08-03 14:33 UTC, KEichenseer requested changes
Hi Joseph,

thanks for contributing your function! It works well, except possibly for the suff and pref functionality (I did not understand the intended outcome).

I have a few general suggestions, besides the in-line comments: 

- standardise output: return a vector of non-letter names, rather than indices, as you do with the synonyms

- could the synonyms be grouped further? At the moment, the input of three slightly different spellings results in an output of three synonym pairs. Could it be an option to return a list of synonym groups instead, containing the similar names in order of descending frequency? It would also be useful to display the actual frequencies of the spelling variants in the output.

- return warning about non-numeric character in the group column? The "NO_FAMILY_SPECIFIED" in the tetrapod example is obviously not an actual family

- Provide better explanation for pref and suff behaviour. With my test data, I did not notice that pref made any difference even though I adjusted the target similarity to try and get it over the similarity threshold. With suff, . It's hard for me to understand why this is as I don't quite get the intended behaviour.

2022-08-03 15:19 UTC, jf15558 commented on R/tax_check.R
> +#' @return \code{list}. A list with two elements. The first element
Implemented. List is only returned if verbose = TRUE and the first element is the data.frame

2022-08-03 15:20 UTC, jf15558 commented on R/tax_check.R
> +#' contains the most common synonym in each pair, the second column 'lesser'
Implemented

2022-08-03 15:24 UTC, jf15558 commented on R/tax_check.R
> +#' the least common synonym in each pair, and the third column 'group' the
Implemented

2022-08-03 15:31 UTC, jf15558 commented on R/tax_check.R
> +          # set the regex for prefixes and suffixes within a single vector
This is true. By default, this section would have no effect with
the default values, but I have made its implementation conditional for sake of efficiency.

2022-08-03 15:35 UTC, jf15558 commented on R/tax_check.R
> +#' filtered out if they do not share a given number of starting and/or ending
Function documentation updated to clarify that this is the generic functionality

2022-08-03 15:47 UTC, jf15558 commented on R/tax_check.R
> +#' A function for checking for potential spelling variations of the same
Funnily enough, Lewis suggested the opposite edit. I think that 'potential' is better here given that the flagged pairs of names are not definitely synonyms (in fact many will not be)

2022-08-03 15:48 UTC, jf15558 commented on R/tax_check.R
> +#' taxon name. These variations are checked for within higher taxonomic
Implemented

2022-08-03 15:48 UTC, jf15558 commented on R/tax_check.R
> +#' taxon name. These variations are checked for within higher taxonomic
Implemented

2022-08-03 15:50 UTC, jf15558 commented on R/tax_check.R
> +#' @details Where higher taxonomy is provided, but some entries are missing,
Implemented

2022-08-03 15:50 UTC, jf15558 commented on R/tax_check.R
> +#' comparisons will be made within alphabetical groups. The function also
Implemented

2022-08-03 15:52 UTC, jf15558 commented on R/tax_check.R
> +#' supplied, e.g. 'Pro', 'Proto'. High similarity matches resulting from high
Implemented

2022-08-03 15:53 UTC, jf15558 commented on R/tax_check.R
> +#' similarity between such prefixes or suffixes will only be retained if two
Implemented

2022-08-03 16:42 UTC, jf15558 commented on R/tax_check.R
> +#' letters. Penalisation by starting letters is analogous to Jaro-Winkler
Agreed. I've removed this extraneous information and added some detail for the prefix/suffix element of the filtering

2022-08-03 18:00 UTC, LewisAJones commented
> Hi Joseph,
> 
> thanks for contributing your function! It works well, except possibly for the suff and pref functionality (I did not understand the intended outcome).
> 
> I have a few general suggestions, besides the in-line comments:
> 
> * standardise output: return a vector of non-letter names, rather than indices, as you do with the synonyms
> * could the synonyms be grouped further? At the moment, the input of three slightly different spellings results in an output of three synonym pairs. Could it be an option to return a list of synonym groups instead, containing the similar names in order of descending frequency? It would also be useful to display the actual frequencies of the spelling variants in the output.
> * return warning about non-numeric character in the group column? The "NO_FAMILY_SPECIFIED" in the tetrapod example is obviously not an actual family
> * Provide better explanation for pref and suff behaviour. With my test data, I did not notice that pref made any difference even though I adjusted the target similarity to try and get it over the similarity threshold. With suff, . It's hard for me to understand why this is as I don't quite get the intended behaviour.

Thanks for supplying additional comments @KEichenseer!

@jf15558 I was wondering if you felt that the pref and suff arguments are fundamental to this function? I am just wondering if these arguments generate more confusion than their value? I think a lot of the function documentation could be drastically reduced without these arguments. That said, you have definitely spent a lot more time thinking about this than I have, so you probably have a good reason for including it that I am missing!

2022-08-09 12:33 UTC, jf15558 commented on R/tax_check.R
> +#' @examples
Simpler example without pref/suff added to the package. Examples now run during package checking

2022-08-09 17:18 UTC, KEichenseer requested changes
Hi Joe,

thanks for making these changes. If you found this output structure most useful, I'm fine with keeping it.

Regarding the _suff_ and _pref_ arguments, I still find their functionality hard to understand from the description, particularly the use of "filtered out". I suggest to phrase the suffixes like this:
"A vector of suffixes which help distinguish otherwise similar taxon names. Synonyms will only be shown if none or both names of a potential synonym pair bear a given prefix. The default is NULL."

In the details, this is again hard to read: "As such, vectors of prefixes and suffixes can also be supplied and matches will only be discarded if two potential synonyms do not share the same prefix or suffix, even if their similarity exceeds the Jaro filtering threshold. ". I suggest we speak of showing or not showing synonyms, rather than of discarding.

The description of the _pref_ argument is different to that of the _suff_ argument, is that intended?

I still can't get the _pref_ argument to do something, and it is not clear either what the purpose would be. In the tetrapod example, nothing changes when we omit the _pref_ argument. Could you provide a working example, please? If it turns out that the _suff_ argument may be useful, but not the _pref_ argument, we can also drop the latter and keep _suff_.

Thanks,
Kilian

2022-10-05 14:05 UTC, LewisAJones commented
Hi @jf15558,

I hope you're doing well! :-) 

I'm not sure if you're still away on fieldwork or not. I've gone ahead and integrated a lot of @KEichenseer and my comments into the function. I think this is a great little function to include into palaeoverse and we wanted to see this in the initial release. It is now more simplified than you initially intended but I strongly believe that will be more useful for most users. Advanced users will most likely pop over to your fossilbrush package for more advanced functionality. 

@KEichenseer can you have a final check when you have a moment? 

Best,

Lewis

2022-10-06 16:05 UTC, ChristopherDavidDean reviewed
Not many comments here - all seems to be working great. Most of the things I've mentioned are to do with documentation and providing a bit more clarity, but otherwise this is looking in excellent working shape. 

The only thing I will say is that currently it's hard for me to gauge the impact/effectiveness of the function without a good knowledge of taxonomy for a specific group/time period (my own issue!). Basically I wanted to check if there were any common misspellings that were potentially missed by the function, but I'm not sure what those would be (and generally taxonomy isn't my strong point). It might be worth getting Emma or Ale to briefly check this, but equally maybe is overkill - I know this is already pulished on CRAN and in a paper, so it's probably fine. Just me having a bit of stream of conciousness thought! 

Anyway, great work, one step closer!

2022-10-06 16:10 UTC, LewisAJones commented on R/tax_check.R
> +        # otherwise cull by prefixes and suffixes if supplied
Nope, this has been removed!

2022-10-06 16:16 UTC, LewisAJones commented on R/tax_check.R
> +#' 0, and less than 1. Potential synonyms above this threshold are not returned.
Updated to: 

The dissimilarity threshold: a value greater than 0 (completely dissimilar), and less than 1 (completely similar). Potential synonyms above this threshold are not returned. This value is set to 0.05 by default, but the user might wish to experiment with this value for their specific data.

2022-10-06 16:37 UTC, LewisAJones commented
Hey @ChristopherDavidDean, thank you for the review! I've implemented all your comments, they were all pretty great suggestions. 
I've also pushed some fixes here for the bin_spatial and tax_range_geo functions. This is because there has been some updates to function names in the h3jsr package. However, this is currently resulting in an error as it seems the update has not been released for Mac/ubuntu yet... I'll investigate.

2022-10-07 11:18 UTC, LewisAJones approved these changes
I think this function is now ready to be merged! The remaining error is to do with the h3jsr update.

2022-10-07 12:01 UTC, merged